spring.application.name=pedidos
spring.datasource.url=jdbc:mariadb://localhost:3306/pedidosrestaurante
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


#JWT
jwt.secret=7fli98292d21342e3a34db3d3x3530c23b3a3c3e4142434445464748494a4b4c

#JWT tiempo de expiración
jwt.expiration=86400000 

##Aumentamos el limite maximo para poder cargar imagenes mas pesadas 
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Aquí debes colocar tu clave API de Gemini (Va sin comillas)
GEMINI_API_KEY= AIzaSyD_Otc4igkuXjBrShsRljYB2UZ2PDzjeio